### ISSUE TITLE
Usage with videos?

### ISSUE THREAD

**Issue by Pibborn** [bbrister/SIFT3D#16]
Hey, thanks a lot for releasing this. I was wondering if it would be easy, hard or downright impossible to adapt your work to extract descriptors from greyscale videos, which are a 3D domain as well.

Would you mind giving me some pointers in the right direction? Thanks again!

**Comment by bbrister** [comment]
Hi,

Thanks for your interest. I think it would be very easy to use this with grayscale videos. You just have to supply your own code to read the files and format them as a 3D array. You could look at these examples:
https://github.com/bbrister/SIFT3D/blob/master/examples/featuresMatlab.m
https://github.com/bbrister/SIFT3D/blob/master/examples/featuresC.c

Are you working in C or Matlab? If you tell me which language you are using I can give more specific advice.

**Comment by Pibborn** [comment]
I am currently working with Matlab. I use [VideoReader](https://it.mathworks.com/help/matlab/ref/videoreader.html) from the standard library. I am looking at the [detectSift3D.m](https://github.com/bbrister/SIFT3D/blob/master/wrappers/matlab/detectSift3D.m) Matlab wrapper and it does seem like there's no need for medical images, just a 3D array. That's great, VideoReader should probably be OK then!

Could you also help me understand how I could go about changing the descriptor size? Is there any way to have it be larger on some dimension? In your paper, I see you use a 4x4x4 region around the keypoint. My question is whether I could use 2x2x2 a region or a 4x2x2 one.

Thanks again!

**Comment by bbrister** [comment]
Glad to hear the code might work for you. 

Unfortunately the current version of the code cannot change the descriptor size at runtime. If you want 2x2x2, you can try changing the line 

`#define NHIST_PER_DIM 4 // Number of SIFT descriptor histograms per dimension `

which is line #89 in [imutil/imtypes.c](https://github.com/bbrister/SIFT3D/blob/master/imutil/imtypes.h). If you change it to

`#define NHIST_PER_DIM 2`

then you should get a 2x2x2 array of histograms. You will have to re-compile the code after changing this.

You could also try extracting the 4x4x4 array and throwing away the unwanted histograms. The descriptors are grouped into 12-element histograms, and the histograms are ordered in (x, y, z) order. So the first 12 elements are histogram (0,0,0) in (x,y,z) coordinates, the second 12 are (1, 0, 0), etc.

If you just want to change the dimensions of the image window, and not the number of histograms, you could use the 'units' parameter for detectSift3D. For example, say that with the default settings some keypoint would by sampled in a 10x10x10 window. Then with 'units' set to [1,1,2] you would instead sample in a 10x10x5 window. You still get  4x4x4 histograms, but each histogram comes from a rectangular window instead of a cube. This option is used for medical images where you often have a different resolution in z than you do in x and y. The setting [1, 1, 2] means that the x and y resolutions are 1mm, while the z resolution is 2mm. So the sampled window would always be 10x10x10mm, but not necessarily 10x10x10 voxels.

Does that make sense?

**Comment by Pibborn** [comment]
It does, thank you kindly. I had the wrong idea about histogram size being the same as the image window size :) I will be sure to check back with you after I compare this to the original [3D SIFT Scovanner implementation](http://crcv.ucf.edu/source/3D) which I am currently using in my research. Thanks again!

**Comment by Pibborn** [comment]
Hi,
after a few months, I finally found some time to try this out :) this works very well out-of-the-box, and installation was pretty painless, too.

I was just wondering about one thing: if I do something like the following,

`
[descriptors, features] = extractSift3D(keys);`
`
csvwrite('/some/path.csv',features);
`

Then I will get a .csv file with (x, y, t) coordinates at which the SIFT features were detected. Is there any way to also get the scale and octave at which the features were found?

Thank you!

**Comment by bbrister** [comment]
Hi,

I am glad you like the software. In your example the scale are octave are in the keypoint array, for example:

`keys(1).scale`
`keys(1).octave`

correspond to:

`features(1,:)`

Hope that helps!

**Comment by Pibborn** [comment]
It does! Thanks again!

**Comment by Pibborn** [comment]
Sorry but I used MATLAB in my work, so I have no idea how you might go about that in C. Maybe you could open a separate issue requesting a tutorial or practlcal example.

**Comment by bbrister** [comment]
Hi @sudonto ,

To do the same thing in C, you can follow the example [featuresC.c](https://github.com/bbrister/SIFT3D/blob/master/examples/featuresC.c). You have to replace the line calling im_read() with your own video reading code. Then, you have to copy the video data into an Image struct, like im_read() does. This part is not as straightforward, since C lacks a built-in data type for multi-dimensional arrays. 

You can allocate the Image with the function init_im_with_dims() in [imutil/imutil.c](https://github.com/bbrister/SIFT3D/blob/master/imutil/imutil.c). To see how to copy the data into the struct, you might look at read_nii() in [imutil/nifti.c](https://github.com/bbrister/SIFT3D/blob/master/imutil/nifti.c).

I hope that helps.

**Comment by sudonto** [comment]
Quite detailed explanation, will try this. Thank you.

**Comment by sudonto** [comment]
Hi @bbrister ,

Back to your code since 3 days ago, I need your direction on my attempt to get the descriptors from video. I get stuck on copying video data into the struct.

I have read how you copy nifti data into the struct, but since I have limited knowledge reading C code, it is quite difficult to translate the code to copy video data into **each** variable in the struct. For example, how can I get this info: `double ux, uy, uz` from video? 

What I have done (and success) so far:
- allocate the struct using function init_im_with_dims() 
- opening video file
- read frame by frame

Could you help me on this matter? Thank you.

**Comment by bbrister** [comment]
Hi @sudonto ,

The fields  ux, uy and uz describe the units (extent) of the voxels in the x, y and z axes. These are used for 3D medical imaging where each voxel is associated to a physical size. For videos, you could just set them to the default of 1, 1, 1. Or, you might want a different extent in time than in space, for example 1, 1, 2.

Does that answer your question?

**Comment by sudonto** [comment]
Hi @bbrister ,

So these are variables I have to set for computing the descriptors for video:
- im->nx (width of frame)
- im->ny (height of frame)
- im->nz (number of frames)
- im->nx, im->ny, im->nz (will be set based on your suggestion)
- im->nc (RGB -> 3)

Is my understanding correct? Sorry for this dumb question.

**Comment by bbrister** [comment]
Hi @sudonto ,

No worries, it is not a dumb question. You are dealing with internals of the library which are seldom touched.

There are some additional fields to set, such as the strides and actual memory allocation. You can set the strides with the function im_default_stride(). Alternatively, you can set all of this in one go with init_im_with_dims(). 

The assignments above look correct to me, except for im->nc. I forgot to mention that the SIFT detector/descriptor only works on single-channel volumes, not multi-channel. The library supports multi-channel images only for certain functions. You probably want to convert the video to grayscale using a standard RGB-to-grayscale color mapping.
