### ISSUE TITLE
function "rand_rows"

### ISSUE THREAD

**Issue by cslayers** [bbrister/SIFT3D#19]
I am curious about the function rand_rows ,when it selecting enough number of  random rows of groups of matching points to calculate an affine matrix by the function solve_system.
Why it remove most of rows instead of picking serveral rows?
Looking forward to your reply.
Thanks you!
![image](https://user-images.githubusercontent.com/17827646/34646648-93010400-f3a8-11e7-888b-30d06f837c7e.png)
![image](https://user-images.githubusercontent.com/17827646/34646635-750e09b6-f3a8-11e7-943f-1f25bebb01b3.png)

**Comment by bbrister** [comment]
Thanks for the find. This is actually a very old and sloppy part of the code. I think I will rewrite it in the next version. 

A much better algorithm would be to get a list of random row indices using Knuth shuffles, then copy those rows into the output.

However, mathematically speaking, the existing implementation is not incorrect. I never bothered to improve this before, since this function is only used in the RANSAC procedure, which so far hasn't been contributing much to the overall execution time.

**Comment by bbrister** [comment]
Refactored in version 1.4.5
